---

- name: Install NFS utils
  ansible.builtin.package:
    name: nfs-utils
    state: present

- name: Enable and activate the service
  ansible.builtin.systemd:
    name: nfs-server.service
    enabled: true
    state: started
  when: not ansible_check_mode
...
