---

- name: Ensure journal directory is present
  ansible.builtin.file:
    name: /var/log/journal
    state: directory
    owner: root
    group: systemd-journal
    mode: '02755'
    setype: var_log_t


- name: Configure journald
  ansible.builtin.template:
    src: templates/journald.conf.j2
    dest: /etc/systemd/journald.conf
    backup: true
    owner: root
    group: root
    mode: '0644'
  notify: Restart journald
