---

# python3-libselinux       # For copy, file, template, ...
# python3-policycoreutils
- name: Install package to manage SeLinux
  become: true
  ansible.builtin.package:
    name:
      - python3-libselinux        # for seboolean
      - python3-libsemanage       # for seboolean
      - python3-policycoreutils   # for seport

- name: Set necessary SeLinux flags on and persistent
  become: true
  ansible.posix.seboolean:
    name: "{{ item }}"
    state: true
    persistent: true
  loop:
    - httpd_can_network_connect
    - httpd_can_network_relay
  when: not lookup('env', 'MOLECULE_FILE')

- name: Allow backend port in selinux
  community.general.seport:
    ports: "{{ item }}"
    proto: tcp
    setype: http_port_t
    state: present
  loop: "{{ nginx_backends_ports }}"
  when:
    - not lookup('env', 'MOLECULE_FILE')
    - nginx_backends_ports is defined
    - nginx_backends_ports | length > 0

- name: Install Nginx module
  become: true
  ansible.builtin.dnf:
    name: "@nginx"
    state: present
  notify: Enable nginx

- name: Configure Nginx
  become: true
  ansible.builtin.template:
    src: templates/etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    validate: '/usr/sbin/nginx -tc %s'
    mode: '0644'
    owner: root
    group: root
  notify:
    - Restart nginx
    - Enable nginx
