---

- name: Set OS distribution dependent variables
  ansible.builtin.include_vars:
    "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"

- name: Install package to manage SeLinux
  become: true
  ansible.builtin.package:
    name: "{{ __nginx_package_selinux_reqs }}"

- name: Set necessary SeLinux flags on and persistent
  become: true
  ansible.posix.seboolean:
    name: "{{ item }}"
    state: true
    persistent: true
  loop:
    - httpd_can_network_connect
    - httpd_can_network_relay
  when: not lookup('env', 'MOLECULE_FILE')

- name: Allow backend port in selinux
  community.general.seport:
    ports: "{{ item }}"
    proto: tcp
    setype: http_port_t
    state: present
  loop: "{{ nginx_backends_ports }}"
  when:
    - not lookup('env', 'MOLECULE_FILE')
    - nginx_backends_ports is defined
    - nginx_backends_ports | length > 0

- name: Install Nginx module
  become: true
  ansible.builtin.dnf:
    name: "{{ __nginx_package_group }}"
    install_weak_deps: false
    state: present
  notify: Enable nginx

- name: Configure Nginx
  become: true
  ansible.builtin.template:
    src: templates/etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    validate: '/usr/sbin/nginx -tc %s'
    mode: '0644'
    owner: root
    group: root
  notify:
    - Restart nginx
    - Enable nginx
