---

- name: Install Nginx module
  become: true
  ansible.builtin.dnf:
    name: "@nginx"
    state: present
  notify: Enable nginx

- name: Configure Nginx
  become: true
  ansible.builtin.template:
    src: templates/etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    validate: '/usr/sbin/nginx -tc %s'
    mode: '0644'
    owner: root
    group: root
  notify: Restart nginx
