---

- name: Verify
  hosts: molecule
  tasks:

    - name: Get Services facts
      ansible.builtin.service_facts:

    - name: Check if firewalld is running
      ansible.builtin.assert:
        that:
          - ansible_facts.services['firewalld.service'].status == 'enabled'
          - ansible_facts.services['firewalld.service'].state == 'running'

    - name: Try to insert a rule
      ansible.posix.firewalld:
        service: https
        permanent: true
        state: enabled
