---

users_linux:
  - name: sysadm
    user_id: "{{ sysadm_id }}"
    user_shell: "{{ sysadm_shell }}"
    user_home: "{{ sysadm_home }}"
    admins_list: "{{ sysadm_authorized_keys }}"
  - name: "{{ appadm_user }}"
    user_id: "{{ appadm_id }}"
    user_shell: "{{ appadm_shell }}"
    user_home: "{{ appadm_home }}"
    admins_list: "{{ appadm_authorized_keys }}"
