---
all:
  children:
    molecule:
      hosts:
        nfs_client_test_server_el8:
          container_image: registry.access.redhat.com/ubi8/ubi-init
        nfs_client_el8:
          container_image: registry.access.redhat.com/ubi8/ubi-init
      vars:
        ansible_connection: containers.podman.podman
        container_privileged: true
        container_systemd: true
        container_command: "/usr/sbin/init"
        container_security_opt: ['label=disable']

    nfs_servers:
      hosts:
        nfs_client_test_server_el8:

    nfs_clients:
      hosts:
        nfs_client_el8:
