---

- name: Converge
  hosts: sudo1
  gather_facts: false
  vars:
    ansible_user: ansible
  roles:

    - role: sudo
      sudoers_file: 20-user_01
      rules:
        - user: user_01
          commands:
            - '/bin/ls *'
            - '/bin/cat *'
          nopasswd: true
