---

- name: Prepare
  hosts: molecule
  gather_facts: false
  tasks:

    - name: Unmask systemd-logind.service
      ansible.builtin.systemd:
        name: systemd-logind.service
        masked: false

    - name: Create user_01 user
      ansible.builtin.user:
        name: user_01
        state: present
