---

- name: Verify
  hosts: sudo1
  gather_facts: false
  tasks:

    - name: Check if 20-user_01 drop-in file exists
      ansible.builtin.stat:
        path: /etc/sudoers.d/20-user_01
      register: user_01_sudo_file

    - name: Assert that 20-user_01 drop-in file exists
      ansible.builtin.assert:
        that: user_01_sudo_file.stat.exists

    - name: Issue a command as root from user_01
      ansible.builtin.command:
        cmd: sudo ls /root
      changed_when: true
      register: command_from_user_01

    - name: Assert that command sudo ls /root worked without password
      ansible.builtin.assert:
        that: command_from_user_01.rc == 0
