---

- name: Template common_profile for {{ user_name }}
  ansible.builtin.template:
    src: templates/common_profile.j2
    dest: "{{ __user_info.home }}/.common_profile"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0644'
