---
# tasks file for user

- name: Set variables defaults to avoid testing if variables are defined
  set_fact:
    user_path_add: "{{ user_path_add | default([]) }}"
    user_path: "{{ user_path | default('') }}"
    user_uid: "{{ user_uid | default(0) }}"
    user_home: "{{ user_home | default('') }}"
    user_authorized_keys: "{{ user_authorized_keys | default({}) }}"

- name: Assert that {{ user_name }} user_path_add and user_path are not both set
  assert:
    that: not ( user_path_add | length > 0 and  user_path | length > 0 )
    fail_msg: user_path_add and user_path are mutually exclusive

- name: "Add {{ user_name }} user"
  become: true
  user:
    name: "{{ user_name }}"
    state: present
    shell: "{{ user_shell | default('/bin/bash') }}"
    home: "{{ omit if (user_home | length == 0) else user_home }}"
    uid: "{{ omit if ( user_uid | int == 0 ) else ( user_uid | int ) }}"
  register: test_user_data

- name: Get {{ user_name }} informations
  user:
    name: "{{ user_name }}"
  register: user_info

- name: Include tasks to manage {{ user_name }}'s zsh
  import_tasks: zsh.yml
  when:
    - user_shell is defined
    - user_shell == '/bin/zsh'

- name: Include tasks to manage {{ user_name }}'s PATH
  import_tasks: path.yml

- name: Include tasks to manager {{ user_name }}'s authorized keys
  import_tasks: authorized_keys.yml
  when: user_authorized_keys.keys_list is defined

- name: Reset variables in case the role is called multiple times
  set_fact:
    user_path_add: []
    user_path: ''
    user_uid: 0
    user_home: ''
    user_authorized_keys: {}
