---
# tasks file for user

- name: "Add {{ username }} user"
  become: true
  user:
    name: "{{ username }}"
    state: present
    shell: "{{ shell | default('/bin/bash') }}"
    home: "{{ home | default(omit) }}"
    uid: "{{ uid | default(omit) }}"

- name: Include tasks to handle PATH
  import_tasks: path.yml
