---
# tasks file for user

- name: Assert that user_path_add and user_path are not both sets
  assert:
    that: not (user_path_add is defined and user_path is defined)
    fail_msg: user_path_add and user_path are mutually exclusive

- name: "Add {{ username }} user"
  become: true
  user:
    name: "{{ username }}"
    state: present
    shell: "{{ shell | default('/bin/bash') }}"
    home: "{{ home | default(omit) }}"
    uid: "{{ uid | default(omit) }}"

- name: Get {{ username }} informations
  user:
    name: "{{ username }}"
  register: user_info

- name: Include tasks to manage {{ username }}'s zsh
  import_tasks: zsh.yml
  when:
    - shell is defined
    - shell == '/bin/zsh'

- name: Include tasks to manage {{ username }}'s PATH
  import_tasks: path.yml
