---
# tasks file for user

- name: "Add {{ username }} user"
  become: true
  user:
    name: "{{ username }}"
    state: present
    shell: "{{ shell | default('/bin/bash') }}"
    home: "{{ home | default(omit) }}"
    uid: "{{ uid | default(omit) }}"

- name: Get {{ username }} informations
  user:
    name: "{{ username }}"
  register: user_info

- name: Include tasks to manage {{ username }}'s zsh
  import_tasks: zsh.yml
  when: shell == '/bin/zsh'

- name: Include tasks to manage {{ username }}'s PATH
  import_tasks: path.yml
