---

- name: Get {{ username }} informations
  user:
    name: "{{ username }}"
  register: user_info

- name: Add paths to {{ username }} common_profile
  become: true
  template:
    src: templates/common_profile.j2
    dest: "{{ user_info.home }}/.common_profile"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
  when:
    - user_path is not defined
    - user_path_add is defined
    - user_path_add | length > 0

- name: Load common_profile from bash
  become: true
  lineinfile:
    regex: "^source \\$HOME/.common_profile$"
    line: source $HOME/.common_profile
    dest: "{{ user_info.home }}/.bashrc"
    state: present
  when:
    - user_path is defined or user_path_add is defined
    - user_info.shell == '/bin/bash'

# - name: Remove common_profile in case user_path_add was emptied

# .zshrc
# export PATH=/home/david/pear/bin:$PATH
# or
# # append
# path+=('/home/david/pear/bin')
# # or prepend
# path=('/home/david/pear/bin' $path)
# # export to sub-processes (make it inherited by child processes)
# export PATH
