---

- name: Disable ZSH wizard for {{ user_name }}
  ansible.builtin.file:
    path: "{{ __user_info.home }}/.zshrc"
    state: touch
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0644'
    access_time: preserve
    modification_time: preserve

- name: Add .zprofile to load .zshrc in non interactive shell (from ansible)
  ansible.builtin.copy:
    src: files/.zprofile
    dest: "{{ __user_info.home }}/.zprofile"
    backup: true
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0644'
