---

- name: Disable ZSH wizard for {{ username }}
  become: true
  file:
    path: "{{ user_info.home }}/.zshrc"
    state: touch
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
    access_time: preserve
    modification_time: preserve
  when: shell == '/bin/zsh'

- name: Add .zprofile to load .zshrc in non interactive shell (from ansible)
  become: true
  copy:
    src: files/.zprofile
    dest: "{{ user_info.home }}/.zprofile"
    backup: true
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
  when: shell == '/bin/zsh'
