---
galaxy_info:
  role_name: firewalld
  namespace: epfl_si
  author: Laurent Indermühle
  description: Install and configure firewalld
  company: École Polytechnique Fédérale de Lausanne
  license: GPL-3.0-or-later
  min_ansible_version: 2.9

  platforms:
    - name: RHEL
      versions:
        - 8

dependencies: []

collections:
  - ansible.posix
