---

argument_specs:
  # roles/nginx/tasks/main.yml entry point
  main:
    short_description: The main entry point for the nginx role.
    options:
      nginx_ver:
        type: "str"
        default: "1.24"
        description: >-
          The version of the nginx group to install. To see what's
          available on your distribution, run
          ``dnf module list --available``. On RHEL8 it's impossible to
          install something else than Nginx:1.14 because they put it as a
          requirement for the PHP module.
      nginx_user:
        type: "str"
        default: nginx
        description: "The user name for the process"
      nginx_pid:
        type: "str"
        default: /var/run/nginx.pid
        description: "The full path to the PID file"
      nginx_events:
        type: "str"
        default: |
          multi_accept       on;
          worker_connections 65535;
        description:
          "The content of the `events` section of the configuration file"
      nginx_http:
        type: "str"
        default: |
          # Logging
          access_log /var/log/nginx/access.log;
          error_log  /var/log/nginx/error.log warn;
        description:
          "The content of the `http` section of the configuation file, exept for
          the servers."
      nginx_servers:
        type: "list"
        elements: "str"
        default:
          - |
            listen 80;
            server_name test.example.com;
        description:
          "A list of `server` content that will be added inside the `http`
          section of the configuration file."
      nginx_backends_ports:
        type: "list"
        elements: "str"
        required: false
        description:
          "If you wish to use nginx as a reverse proxy. You must specify the
          list of ports you intent to use as backend so we can allow them
          in SeLinux."
