---

# Oh_my_zsh will add many features to ZSH

- name: Install Oh_my_zsh
  become: true
  block:

    # This role will do nothing if the folder ~/.oh-my-zsh
    # already exists. We must include it before downloading
    # plugins or themes
    - name: Use gantsign.oh-my-zsh 3rd party role
      include_role:
        name: gantsign.oh-my-zsh
      vars:
        users:
          - username: "{{ user_linux }}"
            oh_my_zsh:
              theme: mh-hostname
              plugins:
                - git
                - z
                - colored-man-pages
                - docker
                - zsh-syntax-highlighting
      when: not ansible_check_mode

    - name: "Find {{ user_linux }} home path"
      user:
        name: "{{ user_linux }}"
      register: user_vars

    - name: "git clone plugin syntax highlight for {{ user_linux }}"
      become: true
      become_user: "{{ user_linux }}"
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: "{{ user_vars.home }}/.oh-my-zsh/custom/plugins\
          /zsh-syntax-highlighting"
        version: 0.7.1
      when: not ansible_check_mode

    - name: "Download theme mh-hostname for {{ user_linux }}"
      get_url:
        url: "http://raw.githubusercontent.com/Honiix\
          /oh-my-zsh/master/themes/mh-hostname.zsh-theme"
        dest: "{{ user_vars.home }}/.oh-my-zsh/custom/themes"
        owner: "{{ user_linux }}"
        group: "{{ user_linux }}"
        mode: '0755'
      when: not ansible_check_mode

    - name: 'Create empty .z file to prevent warnings'
      copy:
        content: ''
        dest: '{{ user_vars.home }}/.z'
        owner: '{{ user_linux }}'
        group: '{{ user_linux }}'
        mode: '0644'
        force: false
      when: not ansible_check_mode
