---

# Oh_my_zsh will add many features to ZSH

- name: Install Oh_my_zsh
  become: true
  block:

    # This role will do nothing if the folder ~/.oh-my-zsh
    # already exists. We must include it before downloading
    # plugins or themes
    - name: Use gantsign.oh-my-zsh 3rd party role
      include_role:
        name: gantsign.oh-my-zsh
      vars:
        users:
          - username: "{{ user_linux }}"
            oh_my_zsh:
              theme: mh-hostname
              plugins:
                - git
                - z
                - colored-man-pages
                - docker
                - zsh-syntax-highlighting
                - zsh-completions
                - zsh-autosuggestions
      when: not ansible_check_mode

    - name: "Find {{ user_linux }} home path"
      user:
        name: "{{ user_linux }}"
      register: user_linux_vars

    - name: "git clone plugin syntax highlight for {{ user_linux }}"
      become: true
      become_user: "{{ user_linux }}"
      git:
        repo: "{{ zsh_plugins_repos.repo }}"
        dest: "{{ user_linux_vars.home }}/.oh-my-zsh/custom/plugins\
          /{{ zsh_plugins_repos.dest }}"
        version: "{{ zsh_plugins_repos.version }}"
      loop:
        - repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
          dest: zsh-syntax-highlighting
          version: 0.7.1
        - repo: https://github.com/zsh-users/zsh-completions.git
          dest: zsh-completions
          version: 0.31.0
        - repo: https://github.com/zsh-users/zsh-autosuggestions.git
          dest: zsh-autosuggestions
          version: v0.6.4
      loop_control:
        loop_var: zsh_plugins_repos
      when: not ansible_check_mode

    - name: "Download theme mh-hostname for {{ user_linux }}"
      get_url:
        url: "http://raw.githubusercontent.com/Honiix\
          /oh-my-zsh/master/themes/mh-hostname.zsh-theme"
        dest: "{{ user_linux_vars.home }}/.oh-my-zsh/custom/themes"
        owner: "{{ user_linux }}"
        group: "{{ user_linux }}"
        mode: '0755'
      when: not ansible_check_mode

    - name: 'Create empty .z file to prevent warnings'
      copy:
        content: ''
        dest: '{{ user_linux_vars.home }}/.z'
        owner: '{{ user_linux }}'
        group: '{{ user_linux }}'
        mode: '0644'
        force: false
      when: not ansible_check_mode
