---

# Playbook to create users

- name: "Add user {{ user_linux.name }}"
  become: true
  block:

    - name: "Create {{ user_linux.name }} group"
      group:
        name: "{{ user_linux.name }}"
        gid: "{{ user_linux.user_id }}"

    - name: "Add {{ user_linux.name }} user"
      user:
        name: "{{ user_linux.name }}"
        group: "{{ user_linux.name }}"
        shell: "{{ user_linux.user_shell }}"
        home: "{{ user_linux.user_home }}"
        uid: "{{ user_linux.user_id }}"
