---

- name: "Get {{ awscli_user }} informations"
  ansible.builtin.getent:
    database: passwd
    key: "{{ awscli_user }}"
  register: _awscli_getent

- name: "Set {{ awscli_user }} variables"
  ansible.builtin.set_fact:
    _awscli_user_home:
      "{{ _awscli_getent.ansible_facts.getent_passwd[awscli_user][4] }}"

- name: "Create .aws folder to store configuration for {{ awscli_user }}"
  become: yes
  ansible.builtin.file:
    path: "{{ _awscli_user_home }}/.aws"
    state: directory
    owner: "{{ awscli_user }}"
    group: "{{ awscli_user }}"
    mode: 0700

- name: "Configure AWS cli for user {{ awscli_user }}"
  become: yes
  ansible.builtin.template:
    src: "{{ _awscli_config_item.src }}"
    dest: "{{ _awscli_config_item.dest }}"
    owner: "{{ awscli_user }}"
    group: "{{ awscli_user }}"
    mode: 0600
  loop:
    - src: templates/config.j2
      dest: "{{ _awscli_user_home }}/.aws/config"
    - src: templates/credentials.j2
      dest: "{{ _awscli_user_home }}/.aws/credentials"
  loop_control:
    loop_var: _awscli_config_item
