---
# tasks file for awscli

- name: Install AWS CLI v2
  ansible.builtin.import_tasks: install.yml
  when: awscli_state == 'present'

- name: Configure AWS CLI v2
  ansible.builtin.import_tasks: configure.yml
  when:
    - awscli_state == 'present'
    - awscli_user is defined and awscli_user | length > 0

- name: Uninstall AWS CLI v2
  ansible.builtin.import_tasks: uninstall.yml
  when: awscli_state == 'absent'
