---
# tasks file for awscli

- name: Install AWS CLI v2
  ansible.builtin.import_tasks: install.yml
  when: awscli_state == 'present'

- name: Uninstall AWS CLI v2
  ansible.builtin.import_tasks: uninstall.yml
  when: awscli_state == 'absent'
