---

- name: Converge
  hosts: users
  gather_facts: false
  vars:
    ansible_user: ansible
  become: true
  roles:

    - name: Create a user without specified UID
      role: user
      user_name: user_auto_uid

    - name: Create a user with UID > 1000
      role: user
      user_name: user_1012
      user_uid: 1012

    - name: Create a user with UID > 1000 to test modifications
      role: user
      user_name: user_1014
      user_uid: 1014

    - name: Create a user with UID < 1000
      role: user
      user_name: user_344
      user_uid: 344

    - name: Create a user with UID < 1000 to test modifications
      role: user
      user_name: user_346
      user_uid: 346

  tasks:

    # Test the loop with vars taken from the inventory
    - include_role:
        name: user
      vars:
        user_name: "{{ user_item.user_name }}"
        user_shell: "{{ user_item.user_shell | default('/bin/bash') }}"
        user_uid: "{{ user_item.user_uid | default(0) }}"
      loop: "{{ users_to_manage }}"
      loop_control:
        loop_var: user_item
