---
galaxy_info:
  role_name: s3cmd
  author: Laurent Indermühle
  description: Install and configure s3cmd
  company: École Polytechnique Fédérale de Lausanne
  license: MIT
  min_ansible_version: 2.9

  platforms:
    - name: RHEL
      versions:
        - 7
        - 8

dependencies: []
