---
# tasks file for ohmyzsh

- name: Ensure dependencies are installed
  become: true
  package:
    name:
      - zsh
      - git
    state: present

- name: Upload ohmyzsh custom package
  become: true
  become_user: "{{ ohmyzsh_user }}"
  ansible.builtin.unarchive:
    copy: true
    src: files/ohmyzsh.tar.gz
    creates: ~/.oh-my-zsh
    dest: ~/
    owner: "{{ ohmyzsh_user }}"
    group: "{{ ohmyzsh_user }}"
    mode: '0755'

- name: Ensure ~/.common_profile and ~/.z exists
  become: true
  become_user: "{{ ohmyzsh_user }}"
  ansible.builtin.file:
    path: "{{ ohmyzsh_necessary_files_item }}"
    state: touch
    owner: "{{ ohmyzsh_user }}"
    group: "{{ ohmyzsh_user }}"
    mode: '0644'
    access_time: preserve
    modification_time: preserve
  loop:
    - ~/.common_profile
    - ~/.z
  loop_control:
    loop_var: ohmyzsh_necessary_files_item

- name: Create the .zshrc file
  become: true
  become_user: "{{ ohmyzsh_user }}"
  template:
    src: templates/zshrc.j2
    dest: ~/.zshrc
    owner: "{{ ohmyzsh_user }}"
    group: "{{ ohmyzsh_user }}"
    mode: '0644'
    force: false
    backup: true
