---
# tasks file for ohmyzsh

- name: Ensure dependencies are installed
  become: true
  package:
    name:
      - zsh
      - git
    state: present

- name: Ensure oh-my-zsh folder is present
  become: true
  become_user: "{{ ohmyzsh_user }}"
  file:
    path: ~/.oh-my-zsh
    state: directory
    owner: "{{ ohmyzsh_user }}"
    group: "{{ ohmyzsh_user }}"
    mode: 0700

- name: Init and configure GIT
  become: true
  become_user: "{{ ohmyzsh_user }}"
  shell:
    cmd: >
      git init ~/.oh-my-zsh
      && cd ~/.oh-my-zsh
      && git config core.eol lf
      && git config core.autocrlf false
      && git config fsck.zeroPaddedFilemode ignore
      && git config fetch.fsck.zeroPaddedFilemode ignore
      && git config receive.fsck.zeroPaddedFilemode ignore
      && git config oh-my-zsh.remote origin
      && git config oh-my-zsh.branch master
      && git remote add origin https://github.com/ohmyzsh/ohmyzsh.git
      && git fetch --depth=1 origin
      && git checkout -b master origin/master
    creates: ~/.oh-my-zsh/.git

- name: Install plugins
  become: true
  become_user: "{{ ohmyzsh_user }}"
  git:
    dest: ~/.oh-my-zsh/custom/plugins/{{ item.dest }}
    repo: "{{ item.repo }}"
    depth: 1
    update: false
  loop:
    - dest: zsh-autosuggestions
      repo: https://github.com/zsh-users/zsh-autosuggestions.git
    - dest: zsh-completions
      repo: https://github.com/zsh-users/zsh-completions.git
    - dest: zsh-syntax-highlighting
      repo: https://github.com/zsh-users/zsh-syntax-highlighting.git

- name: Download mh-hostname theme
  become: true
  become_user: "{{ ohmyzsh_user }}"
  get_url:
    url:
      "http://raw.githubusercontent.com/Honiix/oh-my-zsh/master/themes\
      /mh-hostname.zsh-theme"
    dest: ~/.oh-my-zsh/custom/themes
    checksum: >
      sha256:ea5e6863ae79a95aca113dcdb5579e608a7417c0fe33625dfaa94a4b97b02793

- name: Ensure ~/.common_profile and ~/.z exists
  become: true
  become_user: "{{ ohmyzsh_user }}"
  ansible.builtin.file:
    path: "{{ ohmyzsh_necessary_files_item }}"
    state: touch
    owner: "{{ ohmyzsh_user }}"
    group: "{{ ohmyzsh_user }}"
    mode: '0644'
    access_time: preserve
    modification_time: preserve
  loop:
    - ~/.common_profile
    - ~/.z
  loop_control:
    loop_var: ohmyzsh_necessary_files_item

# Must use force because role epfl_si.rhel.user creates an empty .zshrc file
- name: Create the .zshrc file
  become: true
  become_user: "{{ ohmyzsh_user }}"
  template:
    src: templates/zshrc.j2
    dest: ~/.zshrc
    owner: "{{ ohmyzsh_user }}"
    group: "{{ ohmyzsh_user }}"
    mode: '0644'
    force: true
    backup: true
