---

# Copy the template into user home dir

- name: Find users home path
  become: true
  getent:
    database: passwd
    key: '{{ user_info.user }}'
  loop: "{{ s3cmd_users_access }}"
  loop_control:
    loop_var: user_info
    label: "{{ user_info.user | default('Unset') }}"
  register: users_vars

- name: Store home path per user
  set_fact:
    users_home:
      "{{ users_home | default({})
      | combine({user_vars.user_info.user:
      user_vars.ansible_facts.getent_passwd[user_vars.user_info.user][4]}) }}"
  loop: "{{ users_vars.results }}"
  loop_control:
    loop_var: user_vars
    label: "User: {{ user_vars.user_info.user | default('Unset') }}"

- name: Create the s3cfg file into user home folder
  become: true
  become_user: "{{ user_access.user }}"
  template:
    src: templates/s3cfg.j2
    dest:
      "{{ users_home[user_access.user] }}/.s3cfg-\
      {{ user_access.bucket }}\
      {%- if user_access.grant == 'read_only' -%}\
      -ro\
      {%- elif user_access.grant == 'read_write' -%}\
      -rw\
      {%- endif -%}"
    owner: "{{ user_access.user }}"
    group: "{{ user_access.user }}"
    mode: '0600'
  loop: "{{ s3cmd_users_access }}"
  loop_control:
    loop_var: user_access
    label: "User: {{ user_access.user }}, Bucket: {{ user_access.bucket }}"

- name: Create the default s3cfg file into user home folder
  become: true
  become_user: "{{ user_access.user }}"
  template:
    src: templates/s3cfg.j2
    dest: "{{ users_home[user_access.user] }}/.s3cfg"
    owner: "{{ user_access.user }}"
    group: "{{ user_access.user }}"
    mode: '0600'
  loop: "{{ s3cmd_users_access }}"
  loop_control:
    loop_var: user_access
    label: "User: {{ user_access.user }}, Bucket: {{ user_access.bucket }}"
  when:
    - user_access.default is defined
    - user_access.default is true
