objects:
  role:
    nginx:
      description: The main entry point for the nginx role.
      name: nginx
      version_added: null
    tmux:
      description: The main entry point for the tmux role.
      name: tmux
      version_added: null
    user:
      description: The main entry point for the user role.
      name: user
      version_added: null
plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  filter: {}
  httpapi: {}
  inventory: {}
  lookup: {}
  module: {}
  netconf: {}
  shell: {}
  strategy: {}
  test: {}
  vars: {}
version: 2.0.2
