---

- name: Prepare
  hosts: molecule
  tasks:

    - name: Prepare - Install packages
      ansible.builtin.package:
        name:
          - unzip
          - sudo  # for become
        state: present

    - name: Prepare - Create user john
      ansible.builtin.user:
        name: john
        state: present
