---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: awscli
  gather_facts: false
  tasks:

  - name: Get john profiles
    become: yes
    become_user: john
    ansible.builtin.command:
      cmd: "/usr/local/bin/aws configure list-profiles"
    register: john_profiles
    changed_when: no

  - name: Assert that john has 4 profiles
    assert:
      that: "{{ john_profiles.stdout_lines | length == 4 }}"

  - name: Get root profiles
    become: yes
    ansible.builtin.command:
      cmd: "/usr/local/bin/aws configure list-profiles"
    register: root_profiles
    changed_when: no

  - name: Assert that root has 3 profiles
    assert:
      that: "{{ root_profiles.stdout_lines | length == 3 }}"
