---
all:
  children:
    molecule:
      hosts:
        sudo_el8:
          container_image: registry.access.redhat.com/ubi8/ubi
        sudo_el9:
          container_image: registry.access.redhat.com/ubi9/ubi
      vars:
        ansible_connection: containers.podman.podman
        container_privileged: true
        container_systemd: true
        container_command: "/usr/sbin/init"
        container_security_opt: ['label=disable']
