---
galaxy_info:
  role_name: sudo
  namespace: epfl_si
  author: Laurent Indermühle
  description: Install and configure sudo
  company: École Polytechnique Fédérale de Lausanne (EPFL)
  license: MIT

  min_ansible_version: '2.11'

  platforms:
    - name: 'EL'
      versions:
        - '8'

  galaxy_tags: []

dependencies: []
