---

my_interface:
  "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['interface'] }}"

firewalld_zones:
  external:
    source:
      - ip: "{{ ip_zone3 }}/32"
    service:
      - {name: ssh, state: disabled}
      - name: mysql
  public:
    interface:
      - name: "{{ my_interface }}"
    service:
      - {name: cockpit, state: disabled}
      - {name: dhcpv6-client, state: disabled}
      - {name: ssh, state: disabled}
  internal:
    source:
      - ip: "{{ ip_zone2 }}/32"
    service:
      - name: ssh
      - name: mysql
      - {name: cockpit, state: disabled}
      - {name: dhcpv6-client, state: disabled}
      - {name: mdns, state: disabled}
      - {name: samba-client, state: disabled}
    port:
      - name: "9999/tcp"
      - name: "42000-42099/tcp"
  mysqld1:
    source:
      - ip: "{{ ip_zone4 }}/32"
    port:
      - name: "33001/tcp"
  mysqld2:
    source:
      - ip: "{{ ip_zone5 }}/32"
    port:
      - name: "33002/tcp"
