---

- name: Converge
  hosts: users
  gather_facts: false
  vars:
    ansible_user: ansible
  become: true
  roles:

    - name: Change umask of the root user
      role: user
      user_name: root
      user_umask: '0006'

    - name: Create a user with default umask
      role: user
      user_name: user_auto_umask

    - name: Create a BASH user with a umask of 0066
      role: user
      user_name: user_bash_0066
      user_umask: '0066'

    - name: Create a ZSH user with a umask of 0066
      role: user
      user_name: user_zsh_0066
      user_shell: /bin/zsh
      user_umask: '0066'
