---

- name: Converge
  hosts: ohmyzsh1
  gather_facts: false
  vars:
    ansible_user: ansible
  roles:

    - role: ohmyzsh
      ohmyzsh_user: user_01
      ohmyzsh_theme: mh-hostname

  tasks:

    - name: Change shell to zsh for user_01
      become: yes
      ansible.builtin.user:
        name: user_01
        shell: /bin/zsh
