---

- name: Converge
  hosts: ohmyzsh
  gather_facts: false
  vars:
    ansible_user: ansible
  roles:

    - role: ohmyzsh
      ohmyzsh_user: user_01
      ohmyzsh_theme: mh-hostname

    - role: ohmyzsh
      ohmyzsh_user: root
      ohmyzsh_theme: mh-hostname
