---

scenario:
  name: default

driver:
  name: podman

platforms:

  - name: ohmyzsh1
    registry: {url: registry.access.redhat.com}
    image: ubi8/ubi
    dockerfile: ../../../../molecule/resources/playbooks/Dockerfile.j2

provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer
      stdout_callback: yaml
    ssh_connection:
      forks: 1
      pipelining: false

verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint --exclude .cache
