---

- name: Prepare
  hosts: ohmyzsh
  gather_facts: false
  tasks:

    - name: Unmask systemd-logind.service
      ansible.builtin.systemd:
        name: systemd-logind.service
        masked: no

    # In ubi8 we are always root. This doesn't reflect a real world
    # scenario when ssh connections to root are forbidden. To help
    # us see when a task need the become directive, we will connect
    # to this unprivileged user.
    - name: Create ansible user
      become: true
      user:
        name: ansible
        state: present

    - name: Allow ansible to sudo without password
      become: true
      copy:
        content: "ansible ALL=(ALL) NOPASSWD: ALL"
        dest: /etc/sudoers.d/10-ansible
        validate: /usr/sbin/visudo -csf %s
        owner: root
        group: root
        mode: '0644'

    - name: Create user_01 user
      become: true
      user:
        name: user_01
        state: present

    - name: Install zsh and chsh
      become: true
      package:
        name:
          - zsh
          - util-linux-user
        state: present
