---

- name: Verify
  hosts: ohmyzsh
  gather_facts: false
  tasks:

    - name: Assert that custom plugins has been installed
      stat:
        path: /home/user_01/.oh-my-zsh/custom/plugins/zsh-completions
      failed_when: not zsh_completions_folder.stat.exists
      register: zsh_completions_folder

    - name: Assert that custom theme has been installed
      stat:
        path: /home/user_01/.oh-my-zsh/custom/themes/mh-hostname.zsh-theme
      failed_when: not mh_hostname_theme.stat.exists
      register: mh_hostname_theme
