---
galaxy_info:
  role_name: journald
  namespace: epfl_si
  author: Laurent Indermühle
  description: Install and configure journald
  company: École Polytechnique Fédérale de Lausanne
  license: MIT
  min_ansible_version: 2.9

  platforms:
    - name: RHEL
      versions:
        - 7
        - 8

dependencies: []

collections: []
