---

- name: Converge
  hosts: molecule
  vars:
    ansible_user: cmadm
  roles:

    - role: epfl_si.rhel.nginx
      nginx_http: |
        # Logging
        access_log             /var/log/nginx/access.log;
        error_log              /var/log/nginx/error.log warn;
      nginx_servers:
        - |
          listen 80;
          server_name test.example.com;
        - |
          listen                 1000;
          server_name            {{ ansible_fqdn }};

          # reverse proxy
          location / {
              proxy_pass                         http://127.0.0.1:3000/;
              proxy_http_version                 1.1;
              proxy_cache_bypass                 $http_upgrade;

              # Proxy headers
              proxy_set_header Host              $host;
              proxy_set_header Upgrade           $http_upgrade;
              proxy_set_header Connection        "upgrade";
              proxy_set_header X-Real-IP         $remote_addr;
          }
      nginx_backends_ports:
        - 1000
        - 3000
