---

- name: Prepare
  hosts: molecule
  gather_facts: false
  vars:
    ansible_user: root
  tasks:

    # In ubi8 we are always root. This doesn't reflect a real world
    # scenario when ssh connections to root are forbidden. To help
    # us see when a task needs the `become` directive, we will connect
    # to this unprivileged user.
    - name: Create ansible user
      ansible.builtin.user:
        name: cmadm
        state: present

    - name: Install required packages for testing
      ansible.builtin.package:
        name:
          - sudo  # On RHEL8, will creates /etc/sudoers.d folder
          - nmap-ncat  # To fake a service (backend of the reverse-proxy)
        state: present

    - name: Allow ansible to sudo without password
      ansible.builtin.copy:
        content: "cmadm ALL=(ALL) NOPASSWD: ALL"
        dest: /etc/sudoers.d/10-cmadm
        validate: /usr/sbin/visudo -csf %s
        owner: root
        group: root
        mode: '0644'

    - name: Crate a bash script to run netcat
      ansible.builtin.copy:
        content: |
          #!/usr/bin/env bash

          while true
          do
            /usr/bin/nc -l -p 3000 -c '/usr/bin/echo \
            -e "HTTP/1.1 200 OK\n\n $(date)"'
          done
        dest: /root/faked_3000.sh
        owner: root
        mode: '0755'

    # https://stackoverflow.com/questions/16640054/minimal-web-server-using-netcat
    - name: Create a fake a service on port 3000
      ansible.builtin.copy:  # noqa risky-file-permissions
        content: |
          [Unit]
          Description=Fake service for testing
          After=network.target

          [Service]
          Type=simple
          ExecStart=/root/faked_3000.sh
          ExecStop=/usr/bin/kill -9 $MAINPID

          [Install]
          WantedBy=multi-user.target
        dest: /usr/lib/systemd/system/faked_3000.service

    - name: Enable fake service
      ansible.builtin.systemd:
        name: faked_3000
        state: restarted
        enabled: true
