---

- name: Verify
  hosts: nginx
  tasks:

    - name: collect facts about system services
      service_facts:
      register: services_state

    - name: Assert that Nginx is running and enabled
      vars:
        s: "{{ services_state.ansible_facts.services['nginx.service'] }}"
      assert:
        that: s.state == 'running'and s.status == 'enabled'

    - name: Test nginx returned code
      ansible.builtin.uri:
        url: http://localhost
        status_code: 200

    # This test is useless regaring SeLinux flags because SeLinux can't be
    # enabled inside a container.
    - name: Test nginx reverse proxy
      ansible.builtin.uri:
        url: http://localhost:1000
        status_code: 200
