---

- name: Prepare
  hosts: molecule
  gather_facts: false
  tasks:

    - name: Create test users
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
      loop:
        - user_wo_tpm
        - user_with_tpm
        - user_options

    - name: Install requirements
      ansible.builtin.package:
        name:
          - tmux
          - git
        state: present
