---

- name: Converge
  hosts: user1
  gather_facts: false
  vars:
    ansible_user: ansible
  roles:

    - role: user
      username: user_01
      shell: /bin/bash

    - role: user
      username: user_02
      shell: /bin/zsh
      uid: 1012
      home: /usr/local/user_02
      user_path_add: ['/user_02_test']
      authorized_keys:
        exclusive: true
        keys_list:
          - comment: 'user1@example.com'
            ssh-key: 'ssh-rsa AAAAB1234'
          - comment: 'user2@example.com'
            ssh-key: 'ssh-ed25519 AAAAB5678'

    - role: user
      username: user_03
      shell: /bin/bash
      user_path_add: ['/user_03_test']

    - role: user
      username: user_04
      user_path: "/usr/bin:/user_04_test"
