---

- name: Converge
  hosts: users
  gather_facts: false
  vars:
    ansible_user: ansible
  roles:

    - role: user
      user_name: root
      user_authorized_keys:
        exclusive: true
        keys_list:
          - comment: 'user1@example.com'
            ssh_key: 'ssh-rsa AAAAB1234'
          - comment: 'user2@example.com'
            ssh_key: 'ssh-ed25519 AAAAB5678'

    - role: user
      user_name: user_01
      user_shell: /bin/bash
      user_umask: '0026'

    - role: user
      user_name: user_02
      user_shell: /bin/zsh
      user_uid: 1012
      user_home: /usr/local/user_02
      user_path_add: ['/user_02_test']
      user_authorized_keys:
        exclusive: true
        keys_list:
          - comment: 'user1@example.com'
            ssh_key: 'ssh-rsa AAAAB1234'
          - comment: 'user2@example.com'
            ssh_key: 'ssh-ed25519 AAAAB5678'
      user_umask: '0027'

    - role: user
      user_name: user_03
      user_shell: /bin/bash
      user_path_add: ['/user_03_test']

    - role: user
      user_name: user_04
      user_path: "/usr/bin:/user_04_test"

    - role: user
      user_name: user_05
      user_uid: 344

  tasks:

    # Test the loop with vars taken from the inventory
    - include_role:
        name: user
      vars:
        user_name: "{{ user_item.user_name }}"
        user_shell: "{{ user_item.shell | default('') }}"
        user_home: "{{ user_item.home | default('') }}"
        user_uid: "{{ user_item.uid | default(0) }}"
        user_path_add: "{{ user_item.user_path_add | default([]) }}"
        user_path: "{{ user_item.user_path | default('') }}"
        user_authorized_keys: "{{ user_item.user_authorized_keys | default({}) }}"
      loop: "{{ users_to_manage }}"
      loop_control:
        loop_var: user_item