---

- name: Converge
  hosts: user1
  roles:

    - role: user
      vars:
        user: my-user
        shell: zsh
        path_add: ['usr/local/bin']
        authorized_keys:
          exlusive: true
          keys:
            - comment: 'user1@example.com'
              key: 'ssh-rsa AAAAB1234'
        sudo:
          - sudoers_file: 20-my-user
            hosts: ALL
            as: sysadm
            commands: ['cmd1', 'cmd2']
            nopasswd: true
