---

- name: Converge
  hosts: all
  gather_facts: false
  vars:
    ansible_user: ansible
  become: true
  roles:

    - role: user
      user_name: user_bash
      user_home: /var/lib/user_bash

    - role: user
      user_name: user_zsh
      user_shell: /bin/zsh
      user_home: /var/lib/user_zsh
