---

scenario:
  name: default

driver:
  name: podman

platforms:

  - name: user-el8
    registry: {url: registry.access.redhat.com}
    image: ubi8/ubi
    dockerfile: ../../../../molecule/resources/playbooks/Dockerfile.j2
    groups: [users]


provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer
      stdout_callback: yaml
    ssh_connection:
      pipelining: false
  inventory:
    links:
      hosts: inventory

verifier:
  name: ansible

lint: |
  set -e
  echo "Run yamllint"
  yamllint .
  echo "Run ansible-lint"
  ansible-lint .
