---

scenario:
  name: default
  test_sequence:
    - dependency
    # - lint  # Disabled, lint done for the whole collection
    # - cleanup  # No cleanup required
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    # - side_effect  # No side_effect configured
    - verify
    # - cleanup  # No cleanup required
    - destroy

driver:
  name: default

platforms:

  - name: user_el8
    registry: {url: registry.access.redhat.com}
    image: ubi8/ubi
    dockerfile: ../../../../molecule/resources/playbooks/Dockerfile.j2

provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer
      stdout_callback: yaml
    ssh_connection:
      pipelining: false

verifier:
  name: ansible
