---

- name: Converge
  hosts: users
  gather_facts: false
  vars:
    ansible_user: ansible
  become: true
  roles:

    - name: Add keys to root user
      role: user
      user_name: root
      user_authorized_keys:
        exclusive: true
        keys_list:
          - comment: 'user1@example.com'
            ssh_key: 'ssh-rsa AAAAB1234'
          - comment: 'user2@example.com'
            ssh_key: 'ssh-ed25519 AAAAB5678'

    - name: Create a ZSH user
      role: user
      user_name: user_zsh
      user_shell: /bin/zsh
      user_authorized_keys:
        exclusive: true
        keys_list:
          - comment: 'user1@example.com'
            ssh_key: 'ssh-rsa AAAAB1234'
          - comment: 'user2@example.com'
            ssh_key: 'ssh-ed25519 AAAAB5678'

    - name: Create a BASH user
      role: user
      user_name: user_bash
      user_shell: /bin/bash
      user_authorized_keys:
        exclusive: true
        keys_list:
          - comment: 'user1@example.com'
            ssh_key: 'ssh-rsa AAAAB1234'
          - comment: 'user2@example.com'
            ssh_key: 'ssh-ed25519 AAAAB5678'

    - name: Add a key to a pre-exising user with exclusive set to OFF
      role: user
      user_name: user_pre_exist
      user_authorized_keys:
        keys_list:
          - comment: 'user2@example.com'
            ssh_key: 'ssh-ed25519 AAAAB5678'

    - name: Create a user to test key deletion
      role: user
      user_name: user_deletion
      user_authorized_keys:
        exclusive: true
        keys_list:
          - comment: 'user1@example.com'
            ssh_key: 'ssh-rsa AAAAB1234'
          - comment: 'user2@example.com'
            ssh_key: 'ssh-ed25519 AAAAB5678'

  tasks:

    # Test the loop with vars taken from the inventory
    - include_role:
        name: user
      vars:
        user_name: "{{ user_item.user_name }}"
        user_shell: "{{ user_item.user_shell | default('/bin/bash') }}"
        user_home: "{{ user_item.user_home | default('') }}"
        user_uid: "{{ user_item.user_uid | default(0) }}"
        user_path_add: "{{ user_item.user_path_add | default([]) }}"
        user_path: "{{ user_item.user_path | default('') }}"
        user_authorized_keys:
          "{{ user_item.user_authorized_keys | default({}) }}"
      loop: "{{ users_to_manage }}"
      loop_control:
        loop_var: user_item
