---

scenario:
  name: novalue

driver:
  options:
    managed: false
    login_cmd_template: "podman exec -ti {instance} bash"
    ansible_connection_options:
      ansible_connection: podman

dependency:
  name: galaxy
  options:
    requirements-file: molecule/default/requirements.yml

# To access DBUS we must disable selinux labels
# NET_ADMIN capability is required to attach an IP and admin of firewall
# pre_build_image: means that the container already has Ansible inside
platforms:

  - name: journald_novalue
    registry: {url: registry.access.redhat.com}
    image: ubi8/ubi-init
    tmpfs: ['/run', '/tmp']
    volumes: ['/sys/fs/cgroup:/sys/fs/cgroup:ro']
    capabilities: ['SYS_ADMIN', 'NET_ADMIN']
    command: "/usr/sbin/init"
    security_opts: ['label=disable']

provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      interpreter_python: auto_silent
  inventory:
    link:
      host_vars: ./host_vars
  playbooks:
    create: ../../../../molecule/resources/playbooks/create.yml
    create-fail: ../../../../molecule/resources/playbooks/create-fail.yml
    destroy: ../../../../molecule/resources/playbooks/destroy.yml

verifier:
  name: ansible
