---

- name: Cleanup
  hosts: zones
  gather_facts: false
  tasks:

    - name: Remove facts cache
      connection: local
      delegate_to: localhost
      file:
        name: ${MOLECULE_SCENARIO_DIRECTORY}/fact_cache
        state: absent
      run_once: true
