---

- name: Cleanup
  hosts: localhost
  connection: local
  tasks:

    - name: Remove facts cache
      ansible.builtin.file:
        name: ${MOLECULE_SCENARIO_DIRECTORY}/fact_cache
        state: absent
