---

scenario:
  name: zones

driver:
  name: podman

# To access DBUS we must disable selinux labels
# NET_ADMIN capability is required to attach an IP and admin of firewall
# pre_build_image: means that the container already has Ansible inside
platforms:

  - name: zone1
    image: localhost/ubi8-init-molecule:1.0.0
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
      - NET_ADMIN
    command: "/usr/sbin/init"
    pre_build_image: true
    security_opts:
      - label=disable
    groups:
      - zones

  - name: zone2
    image: localhost/ubi8-init-molecule:1.0.0
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
      - NET_ADMIN
    command: "/usr/sbin/init"
    pre_build_image: true
    security_opts:
      - label=disable
    groups:
      - zones

  - name: zone3
    image: localhost/ubi8-init-molecule:1.0.0
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
      - NET_ADMIN
    command: "/usr/sbin/init"
    pre_build_image: true
    security_opts:
      - label=disable
    groups:
      - zones

provisioner:
  name: ansible
  log: false
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer
      stdout_callback: yaml
    ssh_connection:
      forks: 4
      pipelining: false
  env:
    ANSIBLE_ROLES_PATH: ../..

verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint .
