---

# We must store the containers dynamically assigned IP addresses to allow
# us to use it in our firewall tests scenario

- name: Prepare
  hosts: zones
  gather_facts: false
  tasks:

    - name: Get IP
      connection: local
      delegate_to: localhost
      shell:
        cmd: >
          podman inspect
          -f "{{ '{{' }} .NetworkSettings.IPAddress {{ '}}' }}"
          {{ inventory_hostname }}
      register: container_ip
      changed_when: false

    - name: Create custom fact folder
      file:
        path: /etc/ansible/facts.d
        state: directory
        recurse: true

    - name: Create custom fact to store IP address
      template:
        src: ./custom_facts.j2
        dest: /etc/ansible/facts.d/molecule.fact
