---

# We must store the containers dynamically assigned IP addresses to allow
# us to use it in our firewall tests scenario

- name: Prepare
  hosts: zones
  gather_facts: false
  tasks:

    # This will fail if you add a network to the container.
    # Here is the output of podman inspect for a container
    # without a network specified at creation:
    #   "NetworkSettings": {
    #       "IPAddress": "10.88.0.110",
    #       "MacAddress": "ae:f1:6d:f0:79:95",
    #       [...]
    #
    # Here is the output of podman inspect for a container
    # with a network attached (podman run --network xxx):
    #   "NetworkSettings": {
    #       "IPAddress": "",
    #       "MacAddress": "",
    #       [...]
    #       "Networks": {
    #           "cni-podman2": {
    #               "IPAddress": "10.89.1.3",
    #               "MacAddress": "66:63:7c:74:1f:d7",
    #               "NetworkID": "cni-podman2",
    #               [...]
    #           }
    #       }
    #
    # But, because we can't attach more than one network to a podman
    # container, we won't use Molecule to test firewalld's interface zones
    - name: Get IP
      connection: local
      delegate_to: localhost
      shell:
        cmd: >
          podman inspect
          -f "{{ '{{' }} .NetworkSettings.IPAddress {{ '}}' }}"
          {{ inventory_hostname }}
      register: container_ip
      changed_when: false

    # iproute provides commands: ip, route, ss, ...
    # iputils provides commands: ping, arping, tracepath, ...
    - name: Install ip packages for debugging
      yum:
        name:
          - iproute
          - iputils
        state: present

    - name: Get default interface name
      shell:
        cmd: ip -0 -4 route show default | awk '{ print $5 }'
      register: container_interface

    - name: Create custom fact folder
      file:
        path: /etc/ansible/facts.d
        state: directory
        recurse: true

    - name: Create custom fact to store IP address
      template:
        src: ./custom_facts.j2
        dest: /etc/ansible/facts.d/molecule.fact
