---

- name: Prepare
  hosts: zones
  gather_facts: false
  module_defaults:
    file:
      owner: root
      group: root
      mode: '0700'
    copy:
      owner: root
      group: root
      mode: '0600'
  tasks:

    - name: Unmask systemd-logind.service
      ansible.builtin.systemd:
        name: systemd-logind.service
        masked: false

    # In ubi8 we are always root. This doesn't reflect a real world
    # scenario when ssh connections to root are forbidden. To help
    # us see when a task need the become directive, we will connect
    # to this unprivileged user.
    - name: Prepare - Create ansible user
      ansible.builtin.user:
        name: cmadm
        state: present

    - name: Prepare - Allow ansible to sudo without password
      ansible.builtin.copy:
        content: "cmadm ALL=(ALL) NOPASSWD: ALL"
        dest: /etc/sudoers.d/10-cmadm
        validate: /usr/sbin/visudo -csf %s
        owner: root
        group: root
        mode: '0644'

    # iproute provides commands: ip, route, ss, ...
    # iputils provides commands: ping, arping, tracepath, ...
    - name: Install ip packages for debugging
      ansible.builtin.yum:
        name:
          - iproute
          - iputils
        state: present

    - name: Prepare ssh keys on zone2
      when: inventory_hostname == "zone2"
      block:

        - name: Zone2 - Ensure .ssh folder exists
          ansible.builtin.file:
            path: /root/.ssh
            state: directory
            owner: root
            group: root
            mode: '0700'

        - name: Prepare - Zone2 - Create ssh keys pair
          ansible.builtin.copy:
            content: |
              -----BEGIN OPENSSH PRIVATE KEY-----
              b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
              QyNTUxOQAAACD+pmOaGiWWwTMugyYgGbHVQG2WmakL87Z7ZyKTdXaKcAAAAJiS891KkvPd
              SgAAAAtzc2gtZWQyNTUxOQAAACD+pmOaGiWWwTMugyYgGbHVQG2WmakL87Z7ZyKTdXaKcA
              AAAEAWJj+uZk1IgGsjSprqgU6dQeR9Xe6kSijbp2YxkbyDUf6mY5oaJZbBMy6DJiAZsdVA
              bZaZqQvztntnIpN1dopwAAAAEGhvbmlpeEBwYW5nb2xpbjEBAgMEBQ==
              -----END OPENSSH PRIVATE KEY-----
            dest: /root/.ssh/id_ed25519
            owner: root
            group: root
            mode: '0400'

    - name: Prepare zone1
      when: inventory_hostname == "zone1"
      block:

        - name: Prepare - Zone1 - Paste zone2's public key in authorized_key file
          ansible.builtin.lineinfile:
            line: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP6mY5oaJZbBMy6DJiAZsdVAbZaZqQvztntnIpN1dopw zone2
            path: /root/.ssh/authorized_keys

        - name: Zone1 - Install servers packages
          ansible.builtin.yum:
            name:
              - openssh-server
              - xinetd
            state: present

        - name: Zone1 - Ensure SSHD server service is running
          ansible.builtin.service:
            daemon_reload: true
            enabled: true
            name: sshd.service
            state: started

        - name: Zone1 - Configure xinetd for port 3306
          ansible.builtin.copy:  # noqa risky-file-permissions
            content: |
              service mysqld
              {
                id          = fake-mysqld
                type        = UNLISTED
                wait        = no
                socket_type = stream
                protocol    = tcp
                port        = 3306
                user        = root
                server      = /usr/sbin/sshd
              }
            dest: /etc/xinetd.d/mysqld

        # Use sshd as a fake server since we installed it earlier
        - name: Zone1 - Configure xinetd for port 33001
          ansible.builtin.copy:  # noqa risky-file-permissions
            content: |
              service mysqld
              {
                id          = fake-mysqld1
                type        = UNLISTED
                wait        = no
                socket_type = stream
                protocol    = tcp
                port        = 33001
                user        = root
                server      = /usr/sbin/sshd
              }
            dest: /etc/xinetd.d/mysqld1

        - name: Zone1 - Configure xinetd for port 33002
          ansible.builtin.copy:  # noqa risky-file-permissions
            content: |
              service mysqld
              {
                id          = fake-mysqld2
                type        = UNLISTED
                wait        = no
                socket_type = stream
                protocol    = tcp
                port        = 33002
                user        = root
                server      = /usr/sbin/sshd
              }
            dest: /etc/xinetd.d/mysqld2

        - name: Zone1 - Enable xinetd
          ansible.builtin.systemd:
            name: xinetd
            state: restarted
            enabled: true
