---

- name: Verify
  hosts: zones
  module_defaults:
    wait_for:
      timeout: 2
  tasks:

    - name: Ping from zone2 to zone1
      command:
        cmd: "ping -W 2 -c 1 {{ ip_zone1 }}"

      register: ping_zone2_to_zone1
      failed_when: false
      changed_when: false
      when: inventory_hostname == "zone2"

    - name: Assert that zone2 can ping zone1
      assert:
        that: ping_zone2_to_zone1.rc == 0
        fail_msg: Ping from zone2 to zone1 failed
        success_msg: Ping from zone2 to zone1 successful
      when: inventory_hostname == "zone2"

    - name: Assert that zone2 is allowed on port 22
      wait_for:
        host: "{{ ip_zone1 }}"
        port: 22
      when: inventory_hostname == "zone2"

    - name: Assert that zone3 is blocked on port 22
      wait_for:
        host: "{{ ip_zone1 }}"
        port: 22
      register: zone3_to_port_22
      failed_when: zone3_to_port_22 is succeeded
      when: inventory_hostname == "zone3"

    - name: Assert that zone2 is allowed on port 3306
      wait_for:
        host: "{{ ip_zone1 }}"
        port: 3306
      when: inventory_hostname == "zone2"

    - name: Assert that zone3 is allowed on port 3306
      wait_for:
        host: "{{ ip_zone1 }}"
        port: 3306
      when: inventory_hostname == "zone3"

    - name: Assert that zone4 is allowed on port 33001
      wait_for:
        host: "{{ ip_zone1 }}"
        port: 33001
      when: inventory_hostname == "zone4"

    - name: Assert that zone5 is allowed on port 33002
      wait_for:
        host: "{{ ip_zone1 }}"
        port: 33002
      when: inventory_hostname == "zone5"

    - name: Assert that zone4 is blocked on port 33002
      wait_for:
        host: "{{ ip_zone1 }}"
        port: 33002
      register: zone4_to_port_33002
      failed_when: zone4_to_port_33002 is succeeded
      when: inventory_hostname == "zone4"

    - name: Assert that zone5 is blocked on port 33001
      wait_for:
        host: "{{ ip_zone1 }}"
        port: 33001
      register: zone5_to_port_33001
      failed_when: zone5_to_port_33001 is succeeded
      when: inventory_hostname == "zone5"
