---

scenario:
  name: default

driver:
  name: podman

# To access DBUS we must disable selinux labels
# NET_ADMIN capability is required to attach an IP and admin of firewall
# pre_build_image: means that the container already has Ansible inside
platforms:

  - name: s3cmd_el8
    registry: &registry {url: registry.access.redhat.com}
    image: ubi8/ubi-init
    tmpfs: &tmpfs ['/run', '/tmp']
    volumes: &volumes ['/sys/fs/cgroup:/sys/fs/cgroup:ro']
    capabilities: &capabilities ['SYS_ADMIN', 'NET_ADMIN']
    command: &command "/usr/sbin/init"
    security_opts: &security_opts ['label=disable']
    groups: ['s3cmd']

  - name: s3cmd_el9
    registry: *registry
    image: ubi9/ubi-init
    tmpfs: *tmpfs
    volumes: *volumes
    capabilities: *capabilities
    command: *command
    security_opts: *security_opts
    groups: ['s3cmd']

provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer
      stdout_callback: yaml
    ssh_connection:
      forks: 4
      pipelining: false
  inventory:
    link:
      group_vars: ./group_vars

verifier:
  name: ansible
