---

- name: Prepare
  hosts: s3cmd
  tasks:

    - name: Install EPEL
      vars:
        ansible_python_interpreter: /usr/bin/python
      ansible.builtin.yum:
        name:
          "https://dl.fedoraproject.org/pub/epel\
          /epel-release-latest-7.noarch.rpm"
        state: present
      when: ansible_facts['distribution_major_version'] == '7'

    - name: Install python3 and pip
      vars:
        ansible_python_interpreter: /usr/bin/python
      ansible.builtin.yum:
        name:
          - python3      # Only python2.7 is available by default
          - python3-pip
      when: ansible_facts['distribution_major_version'] == '7'

    - name: Install pip
      ansible.builtin.dnf:
        name: python3-pip
      when: ansible_facts['distribution_major_version'] == '8'
