---
# tasks file for sudo

- name: Ensure sudo package is installed
  become: true
  ansible.builtin.package:
    name: sudo
    state: present

- name: Create drop-in file for {{ sudo_file }}
  become: true
  ansible.builtin.template:
    src: templates/sudoers.j2
    dest: "/etc/sudoers.d/{{ sudo_file }}"
    owner: root
    group: root
    mode: '0644'
    validate: /usr/sbin/visudo -csf %s
