---
# tasks file for sudo

- name: Ensure sudo package is installed
  become: true
  package:
    name: sudo
    state: present

- name: Create {{ sudo_file }} drop-in file
  become: true
  template:
    src: templates/sudoers.j2
    dest: "/etc/sudoers.d/{{ sudo_file }}"
    owner: root
    group: root
    mode: '0644'
    validate: /usr/sbin/visudo -csf %s
