---

- name: Update services facts
  ansible.builtin.service_facts:

- name: Uninstall iptables on RHEL 8+
  when:
    - ansible_distribution_major_version >= '8'
    - ansible_facts.services['iptables.service'].status is defined
    - ansible_facts.services['iptables.service'].status == 'enabled'
  become: true
  block:

    - name: Backup iptables rules
      ansible.builtin.copy:
        remote_src: true
        src: /etc/sysconfig/iptables
        dest: /root/backup-iptables-rules
        owner: root
        group: root
        mode: '0600'

    - name: Disable iptables service
      ansible.builtin.service:
        name: iptables.service
        enabled: false
        state: stopped

    - name: Uninstall iptables-services package
      ansible.builtin.package:
        name: iptables-services
        state: absent
