---
# tasks file for firewalld

- name: Disable others firwalld
  include_tasks: disable_other_firewalls.yml

- name: Setup firewalld
  include_tasks: setup_firewalld.yml

- name: Setup Ansible dependencies to manage firewalld
  include_tasks: setup_ansible_dependencies.yml

- name: Set zone sources
  include_tasks: set_zone_sources.yml
  loop: "{{ firewalld_zones | dict2items }}"
  loop_control:
    loop_var: firewalld_zone_sources
    label: "{{ firewalld_zone_sources.key }}"
  when:
    - firewalld_zones is defined
    - firewalld_zone_sources.value.source is defined
