---
# tasks file for firewalld

- name: Preflight check
  ansible.builtin.include_tasks:
    file: preflight_checks.yml

- name: Disable others firwalld
  ansible.builtin.include_tasks:
    file: disable_other_firewalls.yml

- name: Setup firewalld
  ansible.builtin.include_tasks:
    file: setup_firewalld.yml

- name: Setup Ansible dependencies to manage firewalld
  ansible.builtin.import_tasks:
    file: setup_ansible_dependencies.yml

- name: Create new zones
  ansible.builtin.include_tasks:
    file: create_new_zones.yml

- name: Set zone sources
  ansible.builtin.include_tasks:
    file: set_zone_sources.yml
  loop: "{{ firewalld_zones | dict2items }}"
  loop_control:
    loop_var: firewalld_zone_sources
    label: "{{ firewalld_zone_sources.key }}"
  when:
    - firewalld_zones is defined
    - firewalld_zone_sources.value.source is defined

- name: Set zone interfaces
  ansible.builtin.include_tasks:
    file: set_zone_interfaces.yml
  loop: "{{ firewalld_zones | dict2items }}"
  loop_control:
    loop_var: firewalld_zone_interfaces
    label: "{{ firewalld_zone_interfaces.key }}"
  when:
    - firewalld_zones is defined
    - firewalld_zone_interfaces.value.interface is defined

- name: Set zone services
  ansible.builtin.include_tasks:
    file: set_zone_services.yml
  loop: "{{ firewalld_zones | dict2items }}"
  loop_control:
    loop_var: firewalld_zone_services
    label: "{{ firewalld_zone_services.key }}"
  when:
    - firewalld_zones is defined
    - firewalld_zone_services.value.service is defined

- name: Set zone ports
  ansible.builtin.include_tasks:
    file: set_zone_ports.yml
  loop: "{{ firewalld_zones | dict2items }}"
  loop_control:
    loop_var: firewalld_zone_ports
    label: "{{ firewalld_zone_ports.key }}"
  when:
    - firewalld_zones is defined
    - firewalld_zone_ports.value.port is defined
