---
# tasks file for firewalld

- name: Disable others firwalld
  include_tasks: disable_other_firewalls.yml

- name: Setup firewalld
  include_tasks: setup_firewalld.yml

- name: Setup Ansible dependencies to manage firewalld
  import_tasks: setup_ansible_dependencies.yml

- name: Create new zones
  include_tasks: create_new_zones.yml

- name: Set zone sources
  include_tasks: set_zone_sources.yml
  loop: "{{ firewalld_zones | dict2items }}"
  loop_control:
    loop_var: firewalld_zone_sources
    label: "{{ firewalld_zone_sources.key }}"
  when:
    - firewalld_zones is defined
    - firewalld_zone_sources.value.source is defined

- name: Set zone interfaces
  include_tasks: set_zone_interfaces.yml
  loop: "{{ firewalld_zones | dict2items }}"
  loop_control:
    loop_var: firewalld_zone_interfaces
    label: "{{ firewalld_zone_interfaces.key }}"
  when:
    - firewalld_zones is defined
    - firewalld_zone_interfaces.value.interface is defined

- name: Set zone services
  include_tasks: set_zone_services.yml
  loop: "{{ firewalld_zones | dict2items }}"
  loop_control:
    loop_var: firewalld_zone_services
    label: "{{ firewalld_zone_services.key }}"
  when:
    - firewalld_zones is defined
    - firewalld_zone_services.value.service is defined

- name: Set zone ports
  include_tasks: set_zone_ports.yml
  loop: "{{ firewalld_zones | dict2items }}"
  loop_control:
    loop_var: firewalld_zone_ports
    label: "{{ firewalld_zone_ports.key }}"
  when:
    - firewalld_zones is defined
    - firewalld_zone_ports.value.port is defined
