---

- name: Set Firewalld zone source
  ansible.posix.firewalld:
    zone: "{{ firewalld_zone_source.key }}"
    permanent: "{{ firewalld_zone_source.value.permanent|default('true') }}"
    immediate: "{{ firewalld_zone_source.value.immediate|default('true') }}"
    state: "{{ firewalld_zone_source.value.state|default('enabled') }}"
    source: "{{ firewalld_zone_source_item }}"
  loop: "{{ firewalld_zone_source.value.source }}"
  loop_control:
    loop_var: firewalld_zone_source_item
