---

- name: Set Firewalld zone source
  become: true
  ansible.posix.firewalld:
    zone: "{{ firewalld_zone_source.key }}"
    permanent: "{{ firewalld_zone_source_item.permanent | default('true') }}"
    immediate: "{{ firewalld_zone_source_item.immediate | default('true') }}"
    state: "{{ firewalld_zone_source_item.state | default('enabled') }}"
    source: "{{ firewalld_zone_source_item.ip }}"
  loop: "{{ firewalld_zone_source.value.source }}"
  loop_control:
    loop_var: firewalld_zone_source_item
