---

- name: Install firewalld
  become: yes
  ansible.builtin.package:
    name: firewalld
    state: present

- name: Configure firewalld
  become: yes
  ansible.builtin.template:
    src: templates/firewalld.conf.j2
    dest: /etc/firewalld/firewalld.conf
    backup: yes
    owner: root
    group: root
    mode: '0644'
  notify: Reload firewalld

# template validate is not usable because firewall-offline-cmd
# --system-config wants a folder, not the content of the file.
- name: Validate the configuration
  become: yes
  ansible.builtin.command:
    cmd: >
      /usr/bin/firewall-offline-cmd --system-config /etc/firewalld
      --check-config
  changed_when: false
  register: firewalld_validate_config_result

- name: Check if configuration is valid
  become: yes
  assert:
    that:
      - "'ERROR' not in firewalld_validate_config_result.stderr"
      - "'WARNING' not in firewalld_validate_config_result.stderr"
    fail_msg: >
      The file /etc/firewalld/firewalld.cmd returned errors or warnings. Fix
      the configuration then run `/usr/bin/firewall-offline-cmd --system-config
      /etc/firewalld --check-config` again

# When we were using Iptable, firewall unit file was mask. We must
# ensure it is unmaked
- name: Start and enable firewalld
  become: yes
  ansible.builtin.systemd:
    name: firewalld.service
    state: started
    enabled: yes
    masked: false
