---

- name: Install python-firewall for Ansible
  become: true
  yum:
    name: python-firewall
  when: ansible_python_version is version('3', '<')

- name: Install python3-firewall for Ansible
  become: true
  yum:
    name: python3-firewall
  when: ansible_python_version is version('3', '>=')
