---
# When we were using Iptable, firewall unit file was mask. We must
# ensure it is unmaked

- name: Install firewalld
  become: true
  yum:
    name: firewalld
    state: present

- name: Start and enable firewalld
  become: true
  systemd:
    name: firewalld.service
    state: started
    enabled: true
    masked: false
