---

- name: Reload firewalld
  become: yes
  ansible.builtin.systemd:
    name: firewalld.service
    state: reloaded

# When we were using Iptable, firewall unit file was mask. We must
# ensure it is unmaked
- name: Start and enable firewalld
  become: yes
  ansible.builtin.systemd:
    name: firewalld.service
    state: started
    enabled: yes
    masked: false
