---

- name: Reload firewalld
  become: true
  ansible.builtin.systemd:
    name: firewalld.service
    state: reloaded

- name: Restart firewalld
  become: true
  ansible.builtin.systemd:
    name: firewalld.service
    state: restarted
