---

- name: Prepare
  hosts: iptables
  tasks:

    - name: Install Iptable package
      become: true
      yum:
        name: iptables-services
        state: present

    - name: Enable iptables
      become: true
      systemd:
        name: iptables.service
        daemon_reload: true
        enabled: true
        state: started
