---

- name: Prepare
  hosts: molecule
  tasks:

    - name: Prepare - Install packages
      ansible.builtin.yum:
        name:
          - sudo  # For become
          - iptables-services
        state: present

    # This prevent the following warning:
    # pam_systemd(sudo:session): Failed to create session: Unit is masked.
    - name: Prepare - Unmask systemd-logind
      ansible.builtin.systemd:
        name: systemd-logind.service
        masked: false

    - name: Prepare - Enable iptables
      ansible.builtin.systemd:
        name: iptables.service
        daemon_reload: true
        enabled: true
        state: started

    # This simulates when our servers were downgraded from
    # firewalld to iptables.
    - name: Prepare - Mask firewalld service
      ansible.builtin.systemd:
        name: firewalld.service
        daemon_reload: true
        masked: true
