---

- name: Verify
  hosts: all
  tasks:

    - name: Start service httpd, if not started
      ansible.builtin.service:
        name: nfs-server
        state: started
      register: nfsd_service
      failed_when: nfsd_service is changed

    - name: Test if port 2049 is respond
      delegate_to: localhost
      ansible.builtin.wait_for:
        host: "{{ item }}"
        port: 2049
        timeout: 5
      loop:
        - "{{ hostvars['nfs_server_el8']['ansible_default_ipv4']['address'] }}"
        # - "{{ hostvars['nfs_server_el9']['ansible_default_ipv4']['address'] }}"
...
