---

scenario:
  name: install

driver:
  name: podman

# To access DBUS we must disable selinux labels
# NET_ADMIN capability is required to attach an IP and admin of firewall
# pre_build_image: means that the container already has Ansible inside
platforms:

  - name: install_el8
    registry: &registry {url: registry.access.redhat.com}
    image: ubi8/ubi-init
    dockerfile: &docker ../../../../molecule/resources/playbooks/Dockerfile.j2
    tmpfs: &tmpfs ['/run', '/tmp']
    volumes: &volumes ['/sys/fs/cgroup:/sys/fs/cgroup:ro']
    privileged: &privileged true
    command: &command "/usr/sbin/init"
    security_opts: &security_opts ['label=disable']

# - name: install_el9
#   registry: *registry
#   image: ubi9/ubi-init
#   dockerfile: *docker
#   tmpfs: *tmpfs
#   volumes: *volumes
#   privileged: *privileged
#   command: *command
#   security_opts: *security_opts

provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer
      stdout_callback: yaml
    ssh_connection:
      forks: 4
      pipelining: false
  inventory:
    links:
      hosts: inv.yml


verifier:
  name: ansible
